# Generated by Django 3.1.2 on 2020-11-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearsofexperience', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=120)),
                ('rateperhour', models.IntegerField(default=500)),
                ('skill_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.skills')),
            ],
        ),
    ]
