# Generated by Django 3.1.2 on 2020-11-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='vanancy',
            field=models.IntegerField(default=1),
        ),
    ]
