# Generated by Django 3.1.2 on 2020-11-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_requirements_vanancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='vanancy',
            new_name='vacancies',
        ),
    ]
