# Generated by Django 3.1.2 on 2020-11-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20201121_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='rateperhour',
            new_name='rate_per_hour',
        ),
        migrations.RenameField(
            model_name='requirements',
            old_name='yearsofexperience',
            new_name='years_of_experience',
        ),
    ]
