# Generated by Django 3.1.2 on 2020-11-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20201122_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
