# Generated by Django 3.1.2 on 2020-11-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_delete_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=120)),
                ('rate_per_hour', models.IntegerField(default=500)),
                ('vacancies', models.IntegerField(default=1)),
                ('skill_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.skills')),
            ],
        ),
    ]
