# Generated by Django 3.1.2 on 2020-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='jobid',
            field=models.CharField(default='JID', max_length=50, unique=True),
        ),
    ]
