# Generated by Django 3.1.2 on 2020-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_requirements_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='jobid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
