# Generated by Django 3.1.2 on 2020-11-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_auto_20201122_0000'),
        ('trainer', '0002_auto_20201122_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('qualification', models.CharField(max_length=120)),
                ('cgpa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('university', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('place', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.skills')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicantProfile',
        ),
    ]
