# Generated by Django 3.1.2 on 2020-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20201123_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
