# Generated by Django 3.1.2 on 2020-11-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20201123_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonProfile',
        ),
    ]
