# Generated by Django 3.1.2 on 2020-11-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_auto_20201124_0209'),
        ('trainer', '0006_personprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=120)),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=120)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('qualification', models.CharField(max_length=120)),
                ('cgpa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('university', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.skills')),
            ],
        ),
    ]
