# Generated by Django 3.1.2 on 2020-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Processing', 'Processing'), ('Rejected', 'Rejected')], default='Applied', max_length=100),
        ),
    ]
