# Generated by Django 3.1.2 on 2020-11-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_auto_20201124_0209'),
        ('trainer', '0008_auto_20201124_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.requirements'),
        ),
    ]
