# Generated by Django 3.1.2 on 2020-11-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20201124_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobid',
            field=models.CharField(max_length=120),
        ),
    ]
