# Generated by Django 3.1.2 on 2020-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_application_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
