# Generated by Django 3.1.2 on 2020-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20201124_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Processing', 'Processing'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=100),
        ),
    ]
